import mongoose, { Schema, Model } from "mongoose";

// Import related models to ensure they're registered
import { RangeSession } from "./RangeSession";
import { Firearm } from "./Firearm";
import { Caliber } from "./Caliber";
import { Optic } from "./Optic";

export interface ITargetSheet {
  _id?: mongoose.Types.ObjectId;
  userId?: mongoose.Types.ObjectId;
  rangeSessionId: mongoose.Types.ObjectId;
  firearmId: mongoose.Types.ObjectId;
  caliberId: mongoose.Types.ObjectId;
  opticId: mongoose.Types.ObjectId;
  distanceYards: number;
  slug: string;
  sheetLabel?: string;
  notes?: string;
  photoUrl?: string;
  
  // NEW: Target template fields
  targetTemplateId?: mongoose.Types.ObjectId;
  targetTemplateVersion?: number;
  aimPointCountSnapshot?: number; // Quick stats without loading template
  
  createdAt: Date;
  updatedAt: Date;
}

const TargetSheetSchema = new Schema<ITargetSheet>(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User" },
    rangeSessionId: { type: Schema.Types.ObjectId, ref: "RangeSession", required: true },
    firearmId: { type: Schema.Types.ObjectId, ref: "Firearm", required: true },
    caliberId: { type: Schema.Types.ObjectId, ref: "Caliber", required: true },
    opticId: { type: Schema.Types.ObjectId, ref: "Optic", required: true },
    distanceYards: { type: Number, required: true },
    slug: { type: String, default: '' }, // Auto-generated by pre-save hook
    sheetLabel: { type: String },
    notes: { type: String },
    photoUrl: { type: String },
    
    // NEW: Target template fields
    targetTemplateId: { type: Schema.Types.ObjectId, ref: "TargetTemplate" },
    targetTemplateVersion: { type: Number },
    aimPointCountSnapshot: { type: Number },
  },
  { timestamps: true }
);

// Generate slug before validation
TargetSheetSchema.pre('validate', async function() {
  if (this.isNew && !this.slug) {
    // We'll need to populate the references to build the slug
    const [session, firearm, caliber] = await Promise.all([
      RangeSession.findById(this.rangeSessionId),
      Firearm.findById(this.firearmId),
      Caliber.findById(this.caliberId),
    ]);

    if (!session) {
      throw new Error('Session not found');
    }
    if (!firearm) {
      throw new Error('Firearm not found');
    }
    if (!caliber) {
      throw new Error('Caliber not found');
    }

    // Create base slug: sessionDate-firearmName-caliberName-distance
    const dateStr = session.date.toISOString().split('T')[0];
    const firearmSlug = firearm.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    const caliberSlug = caliber.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    const baseSlug = `${dateStr}-${firearmSlug}-${caliberSlug}-${this.distanceYards}yd`;
    
    // Check if slug exists and append counter if needed
    let slug = baseSlug;
    let counter = 1;
    
    // Use the TargetSheet model reference instead of mongoose.models
    const TargetSheetModel = mongoose.models.TargetSheet || mongoose.model<ITargetSheet>("TargetSheet", TargetSheetSchema);
    while (await TargetSheetModel.findOne({ slug, _id: { $ne: this._id } })) {
      slug = `${baseSlug}-${counter}`;
      counter++;
    }
    
    this.slug = slug;
  }
});

export const TargetSheet: Model<ITargetSheet> =
  mongoose.models.TargetSheet ||
  mongoose.model<ITargetSheet>("TargetSheet", TargetSheetSchema);

